/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-07-18 00:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.spring.service.*;
import com.spring.entity.*;
import java.util.*;

public final class addRecipe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1490952537563L));
    _jspx_dependants.put("jar:file:/D:/workspace6/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMVC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.spring.entity");
    _jspx_imports_packages.add("com.spring.service");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>add Recipe Page</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/D3.css\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" media=\"all\"\r\n");
      out.write("\thref=\"");
      out.print(request.getContextPath());
      out.write("/css/D3_2.css\" />\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/jquery-3.2.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/js/addRecipe.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t.foodDiv{\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmargin-bottom:10px;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 加入食材 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t// \t$(document).on(\"click\", \".addIngre\", function() {\r\n");
      out.write("\r\n");
      out.write("\t// \t\tvar element = $(this);\r\n");
      out.write("\r\n");
      out.write("\t// \t\t$.get(\"createTableServlet\", function(responseText) {\r\n");
      out.write("\r\n");
      out.write("\t// \t\t\telement.parent().before(responseText);\r\n");
      out.write("\t// \t\t});\r\n");
      out.write("\t// \t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 刪除食材 -->\r\n");
      out.write("<script>\r\n");
      out.write("// \tfunction deleteIngredient() {\r\n");
      out.write("\r\n");
      out.write("// \t\t$(document).on('click', \".removebtn\", function(event) {\r\n");
      out.write("\r\n");
      out.write("// \t\t\tvar $this = $(this);\r\n");
      out.write("\r\n");
      out.write("// \t\t\t$this.parent().parent().remove();\r\n");
      out.write("\r\n");
      out.write("// \t\t});\r\n");
      out.write("// \t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 新增組別 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tvar group_no = 1;\r\n");
      out.write("\r\n");
      out.write("\t$(document).on(\"click\", \".addGroup\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar element = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t$.get(\"CreateGroupServlet\", {\r\n");
      out.write("\t\t\tgroup_no : group_no\r\n");
      out.write("\t\t}, function(responseText) {\r\n");
      out.write("\t\t\telement.before(responseText);\r\n");
      out.write("\t\t\tgroup_no++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 刪除群組 -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction deleteGroup() {\r\n");
      out.write("\t\tvar txt;\r\n");
      out.write("\t\tvar r = confirm(\"您確定要刪除這個群組(群組內食材會一併刪除)?\");\r\n");
      out.write("\t\tif (r == true) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(document).on('click', \".deleteGroup\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar $this = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//$(document).load($this.attr('div'));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$this.parent().parent().parent().parent().remove();\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 上傳步驟圖片-->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction stepUploadImg() {\r\n");
      out.write("\t\t$(document).on('change', \".uploadImage\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar $this = $(this).clone().appendTo(\"#testForm\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tfile = $(this)[0].files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\tsibling = $(this).siblings(\"img\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar test = file.name;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar fileName = test.replace(/.*[\\/\\\\]/, '');\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar rcp_seq = fileName.substring(0, 4);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar formData = new FormData($('#testForm')[0]);\r\n");
      out.write("\r\n");
      out.write("\t\t\tformData.append('rcp_seq', rcp_seq);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar str;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"StepUploadServlet/ABC\",\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar src = sibling.attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar res = src.substring(0, 50);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tstr = res + \"step/\" + rcp_seq + \"/\" + fileName;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tsibling.attr(\"src\", str);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#testForm > input').detach();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 新增步驟 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tvar step_no;\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("\t\tstep_no = $(\".stepIndex\").html();\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).on(\"click\", \".addStepBtn\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\tstep_no++;\r\n");
      out.write("\r\n");
      out.write("\t\t$.get(\"createStepBlockServlet.do\", {\r\n");
      out.write("\t\t\tstep_no : step_no\r\n");
      out.write("\t\t}, function(responseText) {\r\n");
      out.write("\t\t\t$(\".test\").before(responseText);\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 刪除步驟 -->\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).on('click', \".stepRemove\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\tvar $this = $(this);\r\n");
      out.write("\r\n");
      out.write("\t\t$(this).parent().parent().parent().parent().remove();\r\n");
      out.write("\r\n");
      out.write("\t\tstep_no--;\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 上傳主照片 -->\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction uploadMainImg() {\r\n");
      out.write("\r\n");
      out.write("\t\t//alert(\"enter uploadMainImg....\");\r\n");
      out.write("\r\n");
      out.write("\t\tvar file;\r\n");
      out.write("\r\n");
      out.write("\t\tvar sibling;\r\n");
      out.write("\r\n");
      out.write("\t\t$(document).on('change', \".uploadMainImage\", function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar $this = $(this).clone().appendTo(\"#testForm\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tfile = $(this)[0].files[0];\r\n");
      out.write("\r\n");
      out.write("\t\t\tsibling = $(this).siblings(\"img\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar test = file.name;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar fileName = test.replace(/.*[\\/\\\\]/, '');\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar rcp_seq = fileName.substring(0, 4);\r\n");
      out.write("\r\n");
      out.write("\t\t\t//.mainImage\r\n");
      out.write("\t\t\tvar formData = new FormData($('#testForm')[0]);\r\n");
      out.write("\r\n");
      out.write("\t\t\tformData.append('rcp_seq', rcp_seq);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar str;\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\turl : \"MainPicUploadServlet\",\r\n");
      out.write("\t\t\t\tcache : false,\r\n");
      out.write("\t\t\t\tdata : formData,\r\n");
      out.write("\t\t\t\tcontentType : false,\r\n");
      out.write("\t\t\t\tprocessData : false,\r\n");
      out.write("\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\tvar src = $(\"#mainImage\").attr(\"src\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar res = src.substring(0, 29);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tstr = res + \"main_picture/\" + rcp_seq + \"/\" + fileName;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t$(\"#mainImage\").attr(\"src\", str);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#testForm > input').detach();\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"o-wrapper\" id=\"o-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/jsp/head.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-8 center-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <button class=\"btn btn-success\" >發佈</button> -->\r\n");
      out.write("\t\t\t\t\t<!-- <button class=\"btn btn-danger\">刪除</button> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" enctype=\"multipart/form-data\"\r\n");
      out.write("\t\t\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/recipe/recipe.do\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<INPUT TYPE=\"SUBMIT\" value=\"儲存\" class=\"btn btn-success\"> <input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"hidden\" name=\"action\" value=\"addRecipe\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<article>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"edit-panel\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<div data-reactroot=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"recipe-paper inner-block\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"recipe-container\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2 class=\"recipe-title clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group required maxlen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control required maxlen\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"請填寫食譜標題\" name=\"rName\" required=\"\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\">剩餘16個字</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- picture-frame -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"mainImage\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/images/upload.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\talt=\"\" id=\"mainImage\" width=\"360px\" height=\"270px\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"upfile\" class=\"uploadMainImage\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"uploadMainImg()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"recipe-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>簡介</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group maxlen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control maxlen\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"輸入食譜描述...\" name=\"note\" rows=\"3\" cols=\"10\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tstyle=\"height: 80px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\">剩餘200個字</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-xs-12 col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"servings control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"select optional control-label\"><span>烹調時間</span><span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t(分鐘) </span></label><select class=\"select optional form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"cookTime\"><option value=\"\">未設定</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"45\">45</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"60\">60</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"90\">90</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"120\">120</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"180\">180+</option></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"servings control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"select optional control-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor=\"recipe[servings]\"><span>份量</span><span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t(人份) </span></label><select class=\"select optional form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"serving\"><option value=\"\">未設定</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"4\">4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"5\">5</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"6\">6</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"7\">7</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"8\">8</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"9\">9</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"10\">10+</option></select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"servings control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"select optional control-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor=\"recipe[servings]\"> <span>料理種類</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <select class=\"select optional form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"kindNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">未設定</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"servings control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"select optional control-label\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tfor=\"recipe[servings]\"> <span>烹調方式</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</label> <select class=\"select optional form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"cookWayNo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">未設定</option>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"recipe-ingredients\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t食材 <small>名稱15字內，份量10字內，皆為必填！</small>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"ingredients\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"group group-0\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"\" id=\"groupName\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group required maxlen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control required maxlen\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"分組名稱（例如：醬汁）\" name=\"groupName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\trequired=\"\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"addIngreColum\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-add-ingredient addIngre\" id=\"addFoodBtn\">加入食材</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!--第二組食材 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-add-group addGroup\">加入分組</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"recipe-steps\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t步驟 <small>可以一次上傳多張圖片</small> <a\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-add-step addStepBtn\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"steps step-img-pull\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"step fadeIn\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"media\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fileupload-processing step-img pull-left\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img alt=\"step-cover\" class=\"img-responsive\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/images/upload.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"file\" name=\"upfile\" class=\"uploadImage\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"stepUploadImg()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"media-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<big class=\"stepIndex\">1</big>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<b>1</b> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"edit-fn order pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a class=\"btn btn-remove destroy stepRemove\"> </a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"step-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group maxlen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"stepBody\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"control-label maxlen hidden\"></label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control maxlen\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"點擊輸入...\" name=\"detail\" rows=\"3\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tcols=\"10\" maxlength=\"150\" style=\"height: 72px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\">剩餘150個字</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<!--下一組步驟 -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"test\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--小撇步 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notes\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h3>小撇步</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group maxlen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea class=\"form-control maxlen\" placeholder=\"點擊輸入...\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"trick\" rows=\"3\" cols=\"10\" style=\"height: 72px;\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"\">剩餘200個字</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<!--小撇步 -->\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</article>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /WEB-INF/views/jsp/addRecipe.jsp(353,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("kindCodeVO");
    // /WEB-INF/views/jsp/addRecipe.jsp(353,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/jsp/addRecipe.jsp(353,15) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kindCodeVO.kindNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${kindCodeVO.kindName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /WEB-INF/views/jsp/addRecipe.jsp(369,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("cookWayCodeVO");
    // /WEB-INF/views/jsp/addRecipe.jsp(369,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/jsp/addRecipe.jsp(369,15) '${cookWayCodeList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cookWayCodeList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookWayCodeVO.cookWayNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cookWayCodeVO.cookWayName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }
}
