/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2017-07-10 01:51:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("\t<div class=\"mega-footer\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row center-block\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-4\">\r\n");
      out.write("\t\t\t\t\t<div class=\"report\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"logo\">&nbsp;</span> <span>© 2011-2017\r\n");
      out.write("\t\t\t\t\t\t\tPolydice, Inc.</span> <span class=\"visible-xs-inline\"> <a\r\n");
      out.write("\t\t\t\t\t\t\trel=\"nofollow\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/terms?ref=icook-footer\">服務條款</a>\r\n");
      out.write("\t\t\t\t\t\t\t和 <a rel=\"nofollow\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/privacy?ref=icook-footer\">隱私權政策</a>\r\n");
      out.write("\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"socials\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden-xs\"><a class=\"footer-social-fb \"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://www.facebook.com/icooktw?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"愛料理 粉絲團\" target=\"_blank\" ref=\"nofollow\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden-xs\"><a class=\"footer-social-line\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://bit.ly/1cfxPqM?ref=icook-footer\" title=\"愛料理 line\"\r\n");
      out.write("\t\t\t\t\t\t\ttarget=\"_blank\" ref=\"nofollow\">&nbsp;</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden-xs\"><a class=\"footer-social-ig\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"http://instagram.com/icooktw?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"愛料理 Instagram\" target=\"_blank\" ref=\"nofollow\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"hidden-xs\"><a class=\"footer-social-twitter\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"https://twitter.com/icooktw?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\ttitle=\"愛料理 推特\" target=\"_blank\" ref=\"nofollow\"></a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=https://help.icook.tw/hc/zh-tw/signin\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"col-xs-12 btn-report\"><span>建議與問題</span></a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-8 pull-right\">\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-links hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t<h4>關於愛料理</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/info?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\" target=\"_blank\">公司資訊</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/jobs?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\" target=\"_blank\">徵才訊息</a>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/contacts/new?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\" target=\"_blank\">廣告合作</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/downloads?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\" target=\"_blank\">品牌資產</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a rel=\"nofollow\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/terms?ref=icook-footer\">服務條款</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a rel=\"nofollow\" target=\"_blank\"\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://newsroom.icook.tw/privacy?ref=icook-footer\">隱私權政策</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-links hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t<h4>會員服務</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"/users/264217527369594/favorites?ref=icook-footer\">我的收藏</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/users/264217527369594\">個人首頁</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/settings?ref=icook-footer\">帳號設定</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/forgot_password?ref=icook-footer\">忘記密碼</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"https://market.icook.tw/orders?ref=icook-footer\">我的訂單</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/vip?ref=icook-footer\">VIP 會員</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-links hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t<h4>逛食譜</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/recipes/popular?ref=icook-footer\">熱門食譜</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/recipes/latest?ref=icook-footer\">新到食譜</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/categories?ref=icook-footer\">全部分類</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"footer-links hidden-xs\">\r\n");
      out.write("\t\t\t\t\t\t<h4>逛其他</h4>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"pull-left\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"https://blog.icook.tw/?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\">生活誌</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"https://atcooking.icook.tw/?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\">享樂誌</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"https://tv.icook.tw/?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\">影音</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"https://market.icook.tw/?ref=icook-footer\"\r\n");
      out.write("\t\t\t\t\t\t\t\trel=\"nofollow\">市集</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
